theme: jekyll-theme-minimal
title: Open Source Branding And Trademarks
logo: /assets/img/lifesaver.png
description: Your simple introduction to practical trademark matters for open source
show_downloads: false
google_analytics: 

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary
social:
  name: Punderthings℠ LLC
  links:
    - http://punderthings.com/
    - http://shanecurcuru.org/
